import {briefingPath,briefingShortId} from '@/lib/briefing-links';
import {sourceName} from '@/lib/catalog';
import {articleTags,tagStyle} from '@/lib/tags';
import {ShareStory} from '@/components/share-story';
export function StoryContent({item:i}:{item:any}){const d=i.document;const evidence=i.evidence;
return <article className="standalone-story"><p>{articleTags(i).map(t=><span className="topic colored-tag" key={t} style={tagStyle(t)}>{t}</span>)}</p><h1>{i.translation?.title || i.title}</h1><div className="briefing-attribution">
{i.cid&&<p><strong>Briefing ID:</strong> <a href={briefingPath(i)}>{briefingShortId(i.cid)}</a></p>}
<p><strong>Publication:</strong> {i.publication||sourceName(i.source_id)}</p>
<p><strong>{i.authors?.length>1?'Authors':'Author'}:</strong> {i.authors?.length?i.authors.join(', '):'Not available in collected metadata'}</p>
{d?.source?.attribution?.affiliation&&<p><strong>Affiliation:</strong> {d.source.attribution.affiliation}</p>}
{i.date_basis==='observation'?<p><strong>Observation period:</strong> {i.observation_period||'Not supplied'} · <strong>Source released:</strong> {i.released_at?new Date(i.released_at).toLocaleString('en-GB',{timeZone:'UTC'})+' UTC':'Not available in collected metadata'}</p>:<p><strong>Source published:</strong> {new Date(i.published_at).toLocaleString('en-GB',{timeZone:'UTC'})} UTC</p>}
{d?.generatedAt&&<p><strong>Briefing created:</strong> {new Date(d.generatedAt).toLocaleString('en-GB',{timeZone:'UTC'})} UTC</p>}
</div><p><a href={i.url} target="_blank" rel="noopener noreferrer">Read full article at source ↗</a></p><p className="muted">{i.evidence_label}{evidence.retrievedAt&&<> Source evidence retrieved {new Date(evidence.retrievedAt).toLocaleString('en-GB',{timeZone:'UTC'})} UTC.</>}</p><ShareStory url={`https://news.bittrees.org${briefingPath(i)}`}/>
{d?<><h2>Briefings</h2><p>{d.briefing.overview}</p><h2>Key points</h2><ul>{d.briefing.points.map((p:string,n:number)=><li key={n}>{p}</li>)}</ul><h2>Context and limitations</h2><p>{d.briefing.limitations}</p><p className="muted">Generated by {d.model} on {new Date(d.generatedAt).toLocaleString('en-GB',{timeZone:'UTC'})} UTC. Based on publisher-provided feed evidence; may not cover the full original article. Check the source for details.</p></>:<><h2>Briefing in preparation</h2><p>{i.translation?.summary||i.summary||i.excerpt}</p><p>An expanded briefing is queued. The original source is available above.</p></>}
{i.cid?<p><a href={`https://ipfs.io/ipfs/${i.cid}`} target="_blank" rel="noopener noreferrer">View archived briefing on IPFS</a><br/><small>{i.cid}</small></p>:<p className="muted">IPFS archive pending.</p>}</article>;}
