import {createHash,createHmac,randomBytes,randomInt,randomUUID,timingSafeEqual} from 'node:crypto';
import {getAddress,verifyMessage} from 'ethers';import {SiweMessage} from 'siwe';
import {pool,tx} from './db';import {HttpError} from './model';import {sendEmail,emailReady} from './mail';
export const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export const token=()=>randomBytes(32).toString('hex');
export const sessionName=process.env.NODE_ENV==='production'?'__Host-news-session':'news-session';
const challengeName=process.env.NODE_ENV==='production'?'__Host-news-challenge':'news-challenge';
export const cookie=(r:Request,n:string)=>r.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith(n+'='))?.slice(n.length+1)||'';
export const setCookie=(name:string,v:string,seconds:number)=>`${name}=${v}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${seconds}${process.env.NODE_ENV==='production'?'; Secure':''}`;
export function checkOrigin(r:Request){const origin=r.headers.get('origin');const allowed=[process.env.APP_URL,process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:''];if(!origin||!allowed.includes(origin))throw new HttpError(403,'This request came from an unrecognized site.');return origin;}
export async function currentAccount(r:Request,required=true){const raw=cookie(r,sessionName);const a=raw?(await pool().query('SELECT a.* FROM sessions s JOIN accounts a ON a.id=s.account_id WHERE s.hash=$1 AND s.expires_at>now()',[hash(raw)])).rows[0]:undefined;if(!a&&required)throw new HttpError(401,'Sign in to manage your newspaper.');return a as {id:string;preferences:unknown}|undefined;}
export async function rateLimit(key:string,max=10){const r=await pool().query("INSERT INTO rate_limits VALUES($1,1,now()+interval '10 minutes') ON CONFLICT(key) DO UPDATE SET hits=CASE WHEN rate_limits.resets_at<now() THEN 1 ELSE rate_limits.hits+1 END,resets_at=CASE WHEN rate_limits.resets_at<now() THEN now()+interval '10 minutes' ELSE rate_limits.resets_at END RETURNING hits",[hash(key)]);if(r.rows[0].hits>max)throw new HttpError(429,'Too many attempts. Try again in ten minutes.');}
function codeHash(id:string,code:string){const s=process.env.AUTH_SECRET;if(!s||s.length<32)throw new HttpError(503,'Sign-in is not configured.');return createHmac('sha256',s).update(id+':'+code).digest('hex');}
export async function startChallenge(r:Request,b:{kind:'email'|'wallet';value:string;purpose:'login'|'link'|'destination';chainId?:number}){
 const origin=checkOrigin(r);const account=b.purpose==='login'?undefined:await currentAccount(r);let value=b.value.trim().toLowerCase();
 await rateLimit('challenge-ip:'+(r.headers.get('x-vercel-forwarded-for')||r.headers.get('x-forwarded-for')||'local'),30);await rateLimit('challenge:'+b.kind+':'+value,5);
 const id=randomUUID(),browser=token(),nonce=randomBytes(16).toString('hex');let message='',secret='';
 if(b.kind==='wallet'){try{value=getAddress(value).toLowerCase();}catch{throw new HttpError(400,'Enter a valid Ethereum wallet address.');}message=new SiweMessage({domain:new URL(origin).host,address:getAddress(value),statement:b.purpose==='destination'?'Verify this wallet for Bittrees News deliveries. No transactions are authorized.':b.purpose==='link'?'Link this wallet to your Bittrees News account. No transactions are authorized.':'Sign in to Bittrees News. No transactions are authorized.',uri:origin,version:'1',chainId:b.chainId||1,nonce,issuedAt:new Date().toISOString(),expirationTime:new Date(Date.now()+600000).toISOString()}).prepareMessage();secret=hash(nonce);}
 else{if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)||value.length>254)throw new HttpError(400,'Enter a valid email address.');if(!emailReady())throw new HttpError(503,'Email sign-in is awaiting sender activation. Wallet sign-in is available.');message=String(randomInt(10000000,100000000));secret=codeHash(id,message);}
 await pool().query("INSERT INTO challenges(id,kind,value,secret_hash,browser_hash,account_id,purpose,payload,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,now()+interval '10 minutes')",[id,b.kind,value,secret,hash(browser),account?.id||null,b.purpose,b.kind==='wallet'?message:null]);
 if(b.kind==='email')try{await sendEmail(value,'Your Bittrees News verification code',`Your verification code is ${message}. It expires in ten minutes.\n\nUse it only at ${origin}. If you did not request this, ignore this email.`,id);}catch(e){await pool().query('DELETE FROM challenges WHERE id=$1',[id]);throw e;}
 return {body:{id,message:b.kind==='wallet'?message:undefined},cookie:setCookie(challengeName,browser,600)};
}
export async function verifyChallenge(r:Request,b:{id:string;proof:string}){
 const origin=checkOrigin(r),browser=cookie(r,challengeName),account=await currentAccount(r,false),session=token();
 const result=await tx(async d=>{const c=(await d.query('SELECT * FROM challenges WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!c||c.consumed||new Date(c.expires_at)<new Date()||c.attempts>=5||c.browser_hash!==hash(browser)||c.account_id&&c.account_id!==account?.id)return {error:'Verification expired. Please start again.'};await d.query('UPDATE challenges SET attempts=attempts+1 WHERE id=$1',[c.id]);let valid=false;
 if(c.kind==='email'){const h=codeHash(c.id,b.proof);valid=timingSafeEqual(Buffer.from(h),Buffer.from(c.secret_hash));}else{try{const m=new SiweMessage(c.payload);valid=m.domain===new URL(origin).host&&m.uri===origin&&hash(m.nonce)===c.secret_hash&&verifyMessage(c.payload,b.proof).toLowerCase()===c.value;}catch{valid=false;}}
 if(!valid)return {error:'The code or signature is incorrect.'};await d.query('UPDATE challenges SET consumed=true WHERE id=$1',[c.id]);
 if(c.purpose==='destination'){const unsub=token();await d.query('INSERT INTO destinations(id,account_id,kind,value,unsubscribe_hash) VALUES($1,$2,$3,$4,$5) ON CONFLICT(account_id,kind,value) DO NOTHING',[randomUUID(),c.account_id,c.kind,c.value,hash(unsub)]);return {destination:true};}
 await d.query('SELECT pg_advisory_xact_lock(hashtext($1))',[c.kind+':'+c.value]);const existing=(await d.query('SELECT account_id FROM identities WHERE kind=$1 AND value=$2',[c.kind,c.value])).rows[0];if(c.account_id&&existing&&existing.account_id!==c.account_id)return {error:'That identity belongs to another account. Sign in with it separately.'};let accountId=c.account_id||existing?.account_id;if(!accountId){accountId=randomUUID();await d.query('INSERT INTO accounts(id) VALUES($1)',[accountId]);}if(!existing)await d.query('INSERT INTO identities(kind,value,account_id) VALUES($1,$2,$3)',[c.kind,c.value,accountId]);await d.query("INSERT INTO sessions VALUES($1,$2,now()+interval '22 hours')",[hash(session),accountId]);await d.query('DELETE FROM sessions WHERE hash=$1',[hash(cookie(r,sessionName))]);return {accountId};});
 if(result.error)throw new HttpError(400,result.error);return {body:{ok:true},cookie:result.accountId?setCookie(sessionName,session,79200):setCookie(challengeName,'',0)};
}
export function authorizeBearer(r:Request,name:string){const secret=process.env[name],auth=r.headers.get('authorization');if(!secret||!auth||!constantEqual(auth,'Bearer '+secret))throw new HttpError(401,'Unauthorized.');}
function constantEqual(a:string,b:string){const aa=Buffer.from(a),bb=Buffer.from(b);return aa.length===bb.length&&timingSafeEqual(aa,bb);}
