// Transaction-local tables: production rows are never touched.
import { Pool } from 'pg';
import { randomUUID } from 'node:crypto';
import assert from 'node:assert/strict';
import { retryStory, saveStoryCid, saveStory } from '../../lib/story-documents';
import { saveTranslation } from '../../lib/translation';
const pool = new Pool({connectionString:process.env.DATABASE_URL});
const client=await pool.connect();
(globalThis as any).newsPool={query:client.query.bind(client),connect:async()=>({query:(sql:string,args?:any[])=>client.query(sql==='BEGIN'?'SAVEPOINT outcome_test':sql==='COMMIT'?'RELEASE SAVEPOINT outcome_test':sql==='ROLLBACK'?'ROLLBACK TO SAVEPOINT outcome_test':sql,args),release:()=>{}})};
try {
 await client.query('BEGIN');
 await client.query('CREATE TEMP TABLE public_job_claims(lease uuid PRIMARY KEY) ON COMMIT DROP');
 await client.query('CREATE TEMP TABLE public_job_events(lease uuid,event text,PRIMARY KEY(lease,event)) ON COMMIT DROP');
 await client.query('CREATE TEMP TABLE items(id text,owner_id uuid) ON COMMIT DROP');
 await client.query('CREATE TEMP TABLE story_documents(item_id text,lease uuid,claimed_at timestamptz,cid text,document jsonb,pinned_at timestamptz,error text,attempts int,available_at timestamptz) ON COMMIT DROP');
 await client.query('CREATE TEMP TABLE translations(key text,lease uuid,status text,claimed_at timestamptz,payload jsonb,attempts int,available_at timestamptz,result jsonb,completed_at timestamptz) ON COMMIT DROP');
 const id='a'.repeat(64),lease=randomUUID(),cid='b'+'a'.repeat(40);
 await client.query('INSERT INTO public_job_claims VALUES($1)',[lease]);
 await client.query('INSERT INTO items VALUES($1,NULL)',[id]);
 await client.query("INSERT INTO story_documents VALUES($1,$2,now()-interval '31 minutes',NULL,'{}',NULL,NULL,1,now())",[id,lease]);
 await client.query("INSERT INTO translations VALUES($1,$2,'working',now()-interval '41 minutes','{}',1,now(),NULL,NULL)",[id,lease]);
 await assert.rejects(saveStoryCid({id,lease,cid}));
 await assert.rejects(retryStory({id,lease,busy:true,error:'busy'}));
 await assert.rejects(saveTranslation({key:id,lease,error:'test'} as any));
 await assert.rejects(saveTranslation({key:id,lease,deferred:true} as any));
 await client.query('ALTER TABLE story_documents ADD COLUMN generated_at timestamptz');
 await client.query('UPDATE story_documents SET claimed_at=now(),document=NULL');
 await client.query('UPDATE translations SET claimed_at=now()');
 await assert.rejects(saveStoryCid({id,lease:randomUUID(),cid}));
 const request={id,lease,model:'test',briefing:{overview:'A factual overview based on the supplied public source evidence.',points:['The source supplies a factual description.'],limitations:'Only the supplied feed evidence is available.'}};
 const saved=await saveStory(request);
 const replay=await saveStory({...request,briefing:{...request.briefing,overview:'A different overview must not replace a previously saved briefing.'}});
 assert.deepEqual(replay,saved);
 await saveStoryCid({id,lease,cid});
 await saveStoryCid({id,lease,cid});
 await assert.rejects(saveStoryCid({id,lease,cid:'b'+'c'.repeat(40)}));
 await assert.rejects(saveStory(request));
 await saveTranslation({key:id,lease,error:'test'} as any);
 assert.equal((await client.query('SELECT cid FROM story_documents')).rows[0].cid,cid);
 assert.equal((await client.query('SELECT status FROM translations')).rows[0].status,'pending');
 assert.equal((await client.query('SELECT available_at=now()+interval \'5 minutes\' AS delayed FROM translations')).rows[0].delayed,true);
 await client.query("UPDATE translations SET status='working',attempts=2,claimed_at=now()");
 await saveTranslation({key:id,lease,error:'test'} as any);
 assert.equal((await client.query('SELECT available_at=now()+interval \'10 minutes\' AS delayed FROM translations')).rows[0].delayed,true);
 assert.deepEqual((await client.query('SELECT event FROM public_job_events ORDER BY event')).rows.map(r=>r.event),['archived','generated','retry']);
 await client.query("UPDATE translations SET status='working',attempts=3,claimed_at=now()");
 await saveTranslation({key:id,lease,error:'test'} as any);
 assert.equal((await client.query('SELECT status FROM translations')).rows[0].status,'failed');
 await client.query("UPDATE translations SET status='working',attempts=2,claimed_at=now()");
 await saveTranslation({key:id,lease,deferred:true} as any);
 const deferred=(await client.query("SELECT status,attempts,available_at=now()+interval '30 seconds' AS delayed FROM translations")).rows[0];
 assert.deepEqual(deferred,{status:'pending',attempts:1,delayed:true});
 await client.query('DELETE FROM public_job_events');
 await client.query('ALTER TABLE public_job_events ADD CONSTRAINT reject_events CHECK(false)');
 await client.query("UPDATE translations SET status='working',attempts=1,claimed_at=now()");
 await assert.rejects(saveTranslation({key:id,lease,error:'test'} as any));
 assert.equal((await client.query('SELECT status FROM translations')).rows[0].status,'working');
 console.log('Outcome idempotency and atomic rollback passed.');
 console.log('Expired and superseded leases rejected; active leases accepted (temporary tables).');
} finally {await client.query('ROLLBACK');client.release();await pool.end();delete (globalThis as any).newsPool;}
