import {sourceEvidence,evidenceLabel} from '@/lib/source-evidence';
import {notFound} from 'next/navigation';
import {pool} from '@/lib/db';
import {sourceName} from '@/lib/catalog';
import {pageMetadata} from '@/lib/seo';
import {articleTags,tagStyle} from '@/lib/tags';
import {ShareStory} from '@/components/share-story';
export const dynamic='force-dynamic';
async function story(id:string){if(!/^[a-f0-9]{64}$/.test(id))return null;return (await pool().query('SELECT i.*,s.document,s.cid,s.generated_at FROM items i LEFT JOIN story_documents s ON s.item_id=i.id WHERE i.id=$1 AND i.owner_id IS NULL',[id])).rows[0];}
export async function generateMetadata({params}:{params:Promise<{id:string}>}){const {id}=await params;const i=await story(id);return i?pageMetadata(i.title,i.document?.briefing.overview?.slice(0,160)||'Source-linked Bittrees briefing',`/story/${id}`):{title:'Story unavailable',robots:{index:false}};}
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;const i=await story(id);if(!i)notFound();const d=i.document;const evidence=d?.evidence||sourceEvidence(i);
return <article className="standalone-story"><p>{articleTags(i).map(t=><span className="colored-tag" key={t} style={tagStyle(t)}>{t}</span>)}</p><h1>{i.title}</h1><p>{i.publication||sourceName(i.source_id)} · {i.authors?.length?i.authors.join(', '):'Author not supplied'} · {new Date(i.published_at).toLocaleString('en-GB',{timeZone:'UTC'})} UTC</p><p><a href={i.url} target="_blank" rel="noopener noreferrer">Read full article at source ↗</a></p><p className="muted">{evidenceLabel(evidence.kind)}{evidence.retrievedAt&&<> Source evidence retrieved {new Date(evidence.retrievedAt).toLocaleString('en-GB',{timeZone:'UTC'})} UTC.</>}</p><ShareStory url={`https://news.bittrees.org/story/${id}`}/>
{d?<><h2>Bittrees summary</h2><p>{d.briefing.overview}</p><h2>Key points</h2><ul>{d.briefing.points.map((p:string,n:number)=><li key={n}>{p}</li>)}</ul><h2>Context and limitations</h2><p>{d.briefing.limitations}</p><p className="muted">Generated by {d.model} on {new Date(d.generatedAt).toLocaleString('en-GB',{timeZone:'UTC'})} UTC. Based on publisher-provided feed evidence; may not cover the full original article. Check the source for details.</p></>:<><h2>Summary in preparation</h2><p>{i.summary||i.excerpt}</p><p>An expanded summary is queued. The original source is available above.</p></>}
{i.cid?<p><a href={`https://ipfs.io/ipfs/${i.cid}`} target="_blank" rel="noopener noreferrer">View archived briefing on IPFS</a><br/><small>{i.cid}</small></p>:<p className="muted">IPFS archive pending.</p>}</article>;}
